name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        experimental: [false]
        include:
          - python-version: "3.x"
            check-latest: true
            experimental: true


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        pip install -e .[tests]

    - name: Show python dependencies
      run: |
        python3 --version
        pip freeze

    - name: Run tests
      run: |
        ./run-tests.sh
